[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
production.PORT = "8000"
production.NODE_ENV = "production"
# Add other required environment variables here
